import { Activity, EmptyState, ListRow, Metric, PageTitle, Panel } from '../../components/common/ui'
import type { Overview } from '../../types/api'

export function OverviewPage({ overview, onQuestion }: { overview: Overview | null; onQuestion: (question: string) => void }) {
  if (!overview) return <EmptyState title="Repository is not indexed" description="Open an indexed repository to view the workspace overview." />

  const questions = [
    'How does the login flow work?',
    'Which files are related to authentication?',
    'Where is JWT validation implemented?',
    'Show me the database models.',
  ]

  return (
    <div>
      <PageTitle title={overview.name} subtitle="AI-powered code understanding for faster navigation, smarter debugging, and grounded answers." />
      <div className="stats-strip">
        <Metric label="Files" value={overview.stats.files} />
        <Metric label="Functions" value={overview.stats.functions} />
        <Metric label="Classes" value={overview.stats.classes} />
        <Metric label="API Endpoints" value={overview.stats.endpoints} />
        <Metric label="Graph Nodes" value={overview.stats.graph_nodes} />
        <Metric label="Indexed Chunks" value={overview.stats.chunks} />
      </div>
      <div className="overview-grid">
        <Panel title="Architecture Summary">
          <div className="architecture-map">
            <span>Client Web</span>
            <span>API Gateway</span>
            <span>Auth Service</span>
            <span>User Service</span>
            <span>Data Layer</span>
          </div>
          <div className="stack-row">{overview.detected_stack.map((item) => <span key={item}>{item}</span>)}</div>
        </Panel>
        <Panel title="Recent Activity">
          <Activity text="Indexed source files" meta="latest run" />
          <Activity text="Updated API schema" meta={`${overview.endpoints.length} endpoints`} />
          <Activity text="Project mental model generated" meta="available" />
        </Panel>
        <Panel title="Suggested Questions">
          {questions.map((question) => <button className="question-row" key={question} onClick={() => onQuestion(question)}>{question}</button>)}
        </Panel>
        <Panel title="Key Modules">
          {overview.modules.map((module) => <ListRow key={module.name} title={module.name} detail={module.summary} meta={`${module.file_count} files`} />)}
        </Panel>
        <Panel title="Important Files">
          {overview.important_files.map((file) => <ListRow key={file.file_path} title={file.file_path} detail={file.reason} />)}
        </Panel>
        <Panel title="Documentation Gaps">
          {overview.documentation_gaps.map((gap) => <ListRow key={gap} title={gap} detail="Generated by current indexing rules." />)}
        </Panel>
      </div>
    </div>
  )
}
