"""Persistence port consumed by repository, indexing, and evidence services."""

from __future__ import annotations

from typing import Protocol

from app.schemas.api import EvidenceDTO
from app.services.index_models import IndexingJobRecord, RepositoryState


class RepositoryStorePort(Protocol):
    def list_repositories(self) -> list[RepositoryState]: ...
    def save_repository(self, repository: RepositoryState) -> None: ...
    def save_repository_metadata(self, repository: RepositoryState) -> None: ...
    def save_indexing_job(self, job: IndexingJobRecord) -> None: ...
    def get_latest_indexing_job(self, repository_id: str) -> IndexingJobRecord | None: ...
    def list_indexing_jobs(self, repository_id: str) -> list[IndexingJobRecord]: ...
    def get_indexing_job(self, repository_id: str, job_id: str) -> IndexingJobRecord | None: ...
    def delete_repository(self, repository_id: str) -> None: ...
    def mark_stale_evidence(self, repository_id: str, current_index_version: int) -> None: ...
    def save_evidence(self, evidence: EvidenceDTO) -> None: ...
    def get_evidence(self, evidence_id: str) -> EvidenceDTO | None: ...
