"""Compatibility exports for the domain-owned API schema modules.

New boundary code should import from the owning module. Existing services keep
this stable surface until their boundaries are migrated by later tasks.
"""

from app.schemas.assistant import (
    ChatRequest,
    ChatResponse,
    CitationDTO,
    EvidenceDTO,
    EvidenceValidationItemDTO,
    EvidenceValidationRequest,
    EvidenceValidationResponse,
    SearchAskWithEvidenceRequest,
)
from app.schemas.auth import (
    AccessOperationResponse,
    ApiTokenCreateRequest,
    ApiTokenIssuedResponse,
    BootstrapRequest,
    LoginRequest,
    SessionIssuedResponse,
    SessionResponse,
)
from app.schemas.exploration import (
    EndpointDTO,
    EndpointListResponse,
    ImportantFileDTO,
    ModuleDTO,
    OverviewResponse,
    ReadingPathItemDTO,
    ReadingPathResponse,
    ReadingPathSignalDTO,
    SymbolDTO,
    SymbolListResponse,
)
from app.schemas.graph import (
    GraphEdgeDTO,
    GraphExpansionRequest,
    GraphExpansionResponse,
    GraphNodeDTO,
    GraphResponse,
    ImpactAnalysisRequest,
    ImpactAnalysisResponse,
    ImpactItemDTO,
    ImpactTargetDTO,
)
from app.schemas.imports import (
    GitHubImportRequest,
    ImportActivityLogDTO,
    ImportCancelResponse,
    ImportConfirmRequest,
    ImportConfirmResponse,
    ImportDuplicateCandidateDTO,
    ImportFileStatisticsDTO,
    ImportIgnoreSummaryDTO,
    ImportPreviewResponse,
    ImportProjectSummaryDTO,
    ImportSecurityWarningDTO,
    ImportSessionCreateResponse,
)
from app.schemas.indexing import (
    FailedFileDTO,
    FailedFilesResponse,
    IndexJobControlResponse,
    IndexJobListResponse,
    IndexJobSummaryDTO,
    IndexRequest,
    IndexResponse,
    IndexStatusResponse,
    IndexWarningDTO,
    IndexWarningsResponse,
    SkippedFileDTO,
    SkippedFilesResponse,
    StalenessResponse,
)
from app.schemas.repositories import (
    RepositoryBulkDeleteRequest,
    RepositoryBulkDeleteResponse,
    RepositoryCreateResponse,
    RepositoryDTO,
    RepositoryDeleteResponse,
)
from app.schemas.search import FileContentResponse, FileTreeNodeDTO, SearchResponse, SearchResultDTO
from app.schemas.settings import IgnorePatternsResponse, SettingsResponse


__all__ = [
    "AccessOperationResponse",
    "ApiTokenCreateRequest",
    "ApiTokenIssuedResponse",
    "BootstrapRequest",
    "ChatRequest",
    "ChatResponse",
    "CitationDTO",
    "EndpointDTO",
    "EndpointListResponse",
    "EvidenceDTO",
    "EvidenceValidationItemDTO",
    "EvidenceValidationRequest",
    "EvidenceValidationResponse",
    "FailedFileDTO",
    "FailedFilesResponse",
    "FileContentResponse",
    "FileTreeNodeDTO",
    "GitHubImportRequest",
    "GraphEdgeDTO",
    "GraphExpansionRequest",
    "GraphExpansionResponse",
    "GraphNodeDTO",
    "GraphResponse",
    "IgnorePatternsResponse",
    "ImpactAnalysisRequest",
    "ImpactAnalysisResponse",
    "ImpactItemDTO",
    "ImpactTargetDTO",
    "ImportantFileDTO",
    "ImportActivityLogDTO",
    "ImportCancelResponse",
    "ImportConfirmRequest",
    "ImportConfirmResponse",
    "ImportDuplicateCandidateDTO",
    "ImportFileStatisticsDTO",
    "ImportIgnoreSummaryDTO",
    "ImportPreviewResponse",
    "ImportProjectSummaryDTO",
    "ImportSecurityWarningDTO",
    "ImportSessionCreateResponse",
    "LoginRequest",
    "IndexJobControlResponse",
    "IndexJobListResponse",
    "IndexJobSummaryDTO",
    "IndexRequest",
    "IndexResponse",
    "IndexStatusResponse",
    "IndexWarningDTO",
    "IndexWarningsResponse",
    "ModuleDTO",
    "OverviewResponse",
    "ReadingPathItemDTO",
    "ReadingPathResponse",
    "ReadingPathSignalDTO",
    "RepositoryBulkDeleteRequest",
    "RepositoryBulkDeleteResponse",
    "RepositoryCreateResponse",
    "RepositoryDTO",
    "RepositoryDeleteResponse",
    "SearchAskWithEvidenceRequest",
    "SearchResponse",
    "SearchResultDTO",
    "SessionIssuedResponse",
    "SessionResponse",
    "SettingsResponse",
    "SkippedFileDTO",
    "SkippedFilesResponse",
    "StalenessResponse",
    "SymbolDTO",
    "SymbolListResponse",
]
