"""production schema baseline

Revision ID: 0001_production_baseline
Revises:
Create Date: 2026-07-13 14:58:17.579479
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0001_production_baseline'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evaluation_datasets',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('version', sa.Text(), nullable=False),
    sa.Column('schema_version', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('artifact_storage_key', sa.Text(), nullable=False),
    sa.Column('artifact_sha256', sa.CHAR(length=64), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("artifact_sha256 ~ '^[0-9a-f]{64}$'", name=op.f('ck_evaluation_datasets_artifact_sha256')),
    sa.CheckConstraint("id LIKE 'dataset_%%'", name=op.f('ck_evaluation_datasets_id_prefix')),
    sa.CheckConstraint("status IN ('draft','frozen','retired')", name=op.f('ck_evaluation_datasets_status')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evaluation_datasets')),
    sa.UniqueConstraint('name', 'version', name='uq_evaluation_datasets_name_version')
    )
    op.create_table('operator_principals',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'active'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("id LIKE 'principal_%%'", name=op.f('ck_operator_principals_id_prefix')),
    sa.CheckConstraint("status IN ('active','disabled')", name=op.f('ck_operator_principals_status')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_operator_principals'))
    )
    op.create_table('evaluation_cases',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('dataset_id', sa.Text(), nullable=False),
    sa.Column('case_key', sa.Text(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('ground_truth', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('expected_evidence', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("id LIKE 'evalcase_%%'", name=op.f('ck_evaluation_cases_id_prefix')),
    sa.CheckConstraint('ordinal >= 0', name=op.f('ck_evaluation_cases_ordinal_nonnegative')),
    sa.ForeignKeyConstraint(['dataset_id'], ['evaluation_datasets.id'], name=op.f('fk_evaluation_cases_dataset_id_evaluation_datasets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evaluation_cases')),
    sa.UniqueConstraint('dataset_id', 'case_key', name='uq_evaluation_cases_key'),
    sa.UniqueConstraint('dataset_id', 'ordinal', name='uq_evaluation_cases_ordinal')
    )
    op.create_table('idempotency_records',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('principal_id', sa.Text(), nullable=False),
    sa.Column('operation', sa.Text(), nullable=False),
    sa.Column('idempotency_key', sa.Text(), nullable=False),
    sa.Column('normalized_request_hash', sa.CHAR(length=64), nullable=False),
    sa.Column('state', sa.Text(), nullable=False),
    sa.Column('http_status', sa.SmallInteger(), nullable=True),
    sa.Column('resource_type', sa.Text(), nullable=True),
    sa.Column('resource_id', sa.Text(), nullable=True),
    sa.Column('response_ref', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("id LIKE 'idem_%%'", name=op.f('ck_idempotency_records_id_prefix')),
    sa.CheckConstraint("normalized_request_hash ~ '^[0-9a-f]{64}$'", name=op.f('ck_idempotency_records_normalized_request_hash_sha256')),
    sa.CheckConstraint("state IN ('in_progress','completed','failed')", name=op.f('ck_idempotency_records_state')),
    sa.CheckConstraint('(resource_type IS NULL) = (resource_id IS NULL)', name=op.f('ck_idempotency_records_resource_pair')),
    sa.CheckConstraint('http_status IS NULL OR http_status BETWEEN 100 AND 599', name=op.f('ck_idempotency_records_http_status')),
    sa.ForeignKeyConstraint(['principal_id'], ['operator_principals.id'], name=op.f('fk_idempotency_records_principal_id_operator_principals'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_idempotency_records')),
    sa.UniqueConstraint('principal_id', 'operation', 'idempotency_key', name='uq_idempotency_scope')
    )
    op.create_table('operator_api_tokens',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('principal_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('token_hash', sa.Text(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("id LIKE 'token_%%'", name=op.f('ck_operator_api_tokens_id_prefix')),
    sa.ForeignKeyConstraint(['principal_id'], ['operator_principals.id'], name=op.f('fk_operator_api_tokens_principal_id_operator_principals'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_operator_api_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_operator_api_tokens_token_hash'))
    )
    op.create_table('operator_sessions',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('principal_id', sa.Text(), nullable=False),
    sa.Column('token_hash', sa.Text(), nullable=False),
    sa.Column('csrf_secret_hash', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("id LIKE 'session_%%'", name=op.f('ck_operator_sessions_id_prefix')),
    sa.ForeignKeyConstraint(['principal_id'], ['operator_principals.id'], name=op.f('fk_operator_sessions_principal_id_operator_principals'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_operator_sessions')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_operator_sessions_token_hash'))
    )
    op.create_table('repositories',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('owner_principal_id', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('lifecycle', sa.Text(), server_default=sa.text("'active'"), nullable=False),
    sa.Column('recovery_state', sa.Text(), server_default=sa.text("'ready'"), nullable=False),
    sa.Column('active_index_version_id', sa.Text(), nullable=True),
    sa.Column('source_freshness', sa.Text(), server_default=sa.text("'unverifiable'"), nullable=False),
    sa.Column('operation_generation', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('deletion_requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("id LIKE 'repo_%%'", name=op.f('ck_repositories_id_prefix')),
    sa.CheckConstraint("lifecycle <> 'deleted' OR (active_index_version_id IS NULL AND deleted_at IS NOT NULL)", name=op.f('ck_repositories_deleted_state')),
    sa.CheckConstraint("lifecycle IN ('active','deleting','deleted')", name=op.f('ck_repositories_repositories_lifecycle')),
    sa.CheckConstraint("recovery_state IN ('ready','blocked')", name=op.f('ck_repositories_repository_recovery_state')),
    sa.CheckConstraint("source_freshness IN ('fresh','possibly_stale','stale','source_missing','unverifiable')", name=op.f('ck_repositories_source_freshness')),
    sa.CheckConstraint('operation_generation >= 0', name=op.f('ck_repositories_operation_generation_nonnegative')),
    sa.ForeignKeyConstraint(['id', 'active_index_version_id'], ['index_versions.repository_id', 'index_versions.id'], name='fk_repositories_active_version', ondelete='RESTRICT', initially='DEFERRED', deferrable=True, use_alter=True),
    sa.ForeignKeyConstraint(['owner_principal_id'], ['operator_principals.id'], name=op.f('fk_repositories_owner_principal_id_operator_principals'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_repositories')),
    sa.UniqueConstraint('id', 'owner_principal_id', name='uq_repositories_owner')
    )
    op.create_index('ix_repositories_lifecycle', 'repositories', ['lifecycle', 'updated_at', 'id'], unique=False)
    op.create_index('ix_repositories_owner_list', 'repositories', ['owner_principal_id', sa.literal_column('created_at DESC'), sa.literal_column('id DESC')], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('principal_id', sa.Text(), nullable=True),
    sa.Column('repository_id', sa.Text(), nullable=True),
    sa.Column('request_id', sa.Text(), nullable=True),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('outcome', sa.Text(), nullable=False),
    sa.Column('resource_type', sa.Text(), nullable=True),
    sa.Column('resource_id', sa.Text(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("id LIKE 'audit_%%'", name=op.f('ck_audit_events_id_prefix')),
    sa.ForeignKeyConstraint(['principal_id'], ['operator_principals.id'], name=op.f('fk_audit_events_principal_id_operator_principals'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], name=op.f('fk_audit_events_repository_id_repositories'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events'))
    )
    op.create_index('ix_audit_events_resource', 'audit_events', ['resource_type', 'resource_id', sa.literal_column('created_at DESC'), sa.literal_column('id DESC')], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('principal_id', sa.Text(), nullable=False),
    sa.Column('repository_id', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), server_default=sa.text("'active'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("id LIKE 'conversation_%%'", name=op.f('ck_conversations_id_prefix')),
    sa.CheckConstraint("status IN ('active','archived','deleted')", name=op.f('ck_conversations_status')),
    sa.ForeignKeyConstraint(['principal_id'], ['operator_principals.id'], name=op.f('fk_conversations_principal_id_operator_principals'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], name=op.f('fk_conversations_repository_id_repositories'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversations'))
    )
    op.create_index('ix_conversations_recent', 'conversations', ['principal_id', 'repository_id', sa.literal_column('updated_at DESC'), sa.literal_column('id DESC')], unique=False)
    op.create_table('repository_deletion_operations',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('repository_id', sa.Text(), nullable=False),
    sa.Column('idempotency_record_id', sa.Text(), nullable=False),
    sa.Column('state', sa.Text(), server_default=sa.text("'queued'"), nullable=False),
    sa.Column('repository_generation', sa.BigInteger(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_error_code', sa.Text(), nullable=True),
    sa.Column('cleanup_summary', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("id LIKE 'delete_%%'", name=op.f('ck_repository_deletion_operations_id_prefix')),
    sa.CheckConstraint("state IN ('queued','running','partially_failed','succeeded','failed')", name=op.f('ck_repository_deletion_operations_deletion_state')),
    sa.CheckConstraint('attempt_count >= 0', name=op.f('ck_repository_deletion_operations_attempt_count_nonnegative')),
    sa.CheckConstraint('repository_generation >= 0', name=op.f('ck_repository_deletion_operations_repository_generation_nonnegative')),
    sa.ForeignKeyConstraint(['idempotency_record_id'], ['idempotency_records.id'], name=op.f('fk_repository_deletion_operations_idempotency_record_id_idempotency_records'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], name=op.f('fk_repository_deletion_operations_repository_id_repositories'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_repository_deletion_operations')),
    sa.UniqueConstraint('idempotency_record_id', name=op.f('uq_repository_deletion_operations_idempotency_record_id'))
    )
    op.create_index('uq_deletion_one_active', 'repository_deletion_operations', ['repository_id'], unique=True, postgresql_where=sa.text("state IN ('queued', 'running', 'partially_failed')"))
    op.create_table('repository_sources',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('repository_id', sa.Text(), nullable=False),
    sa.Column('source_type', sa.Text(), nullable=False),
    sa.Column('canonical_locator', sa.Text(), nullable=True),
    sa.Column('credential_ref', sa.Text(), nullable=True),
    sa.Column('default_ref', sa.Text(), nullable=True),
    sa.Column('last_synchronized_revision', sa.Text(), nullable=True),
    sa.Column('source_fingerprint', sa.CHAR(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("id LIKE 'source_%%'", name=op.f('ck_repository_sources_id_prefix')),
    sa.CheckConstraint("source_fingerprint IS NULL OR (source_fingerprint ~ '^[0-9a-f]{64}$')", name=op.f('ck_repository_sources_source_fingerprint_sha256')),
    sa.CheckConstraint("source_type IN ('upload_zip','upload_folder','public_git')", name=op.f('ck_repository_sources_repository_sources_type')),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], name=op.f('fk_repository_sources_repository_id_repositories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_repository_sources')),
    sa.UniqueConstraint('repository_id', 'id', name='uq_repository_sources_owner')
    )
    op.create_index('uq_repository_source_locator', 'repository_sources', ['repository_id', 'source_type', 'canonical_locator'], unique=True, postgresql_where=sa.text('canonical_locator IS NOT NULL'))
    op.create_table('source_snapshots',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('repository_id', sa.Text(), nullable=False),
    sa.Column('repository_source_id', sa.Text(), nullable=False),
    sa.Column('revision', sa.Text(), nullable=True),
    sa.Column('storage_key', sa.Text(), nullable=False),
    sa.Column('snapshot_sha256', sa.CHAR(length=64), nullable=False),
    sa.Column('policy_version', sa.Text(), nullable=False),
    sa.Column('inventory_schema_version', sa.Text(), nullable=False),
    sa.Column('total_files', sa.BigInteger(), nullable=False),
    sa.Column('total_bytes', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("id LIKE 'snapshot_%%'", name=op.f('ck_source_snapshots_id_prefix')),
    sa.CheckConstraint("snapshot_sha256 ~ '^[0-9a-f]{64}$'", name=op.f('ck_source_snapshots_snapshot_sha256')),
    sa.CheckConstraint('total_bytes >= 0', name=op.f('ck_source_snapshots_total_bytes_nonnegative')),
    sa.CheckConstraint('total_files >= 0', name=op.f('ck_source_snapshots_total_files_nonnegative')),
    sa.ForeignKeyConstraint(['repository_id', 'repository_source_id'], ['repository_sources.repository_id', 'repository_sources.id'], name='fk_source_snapshots_repository_source', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_snapshots')),
    sa.UniqueConstraint('repository_id', 'id', name='uq_source_snapshots_owner'),
    sa.UniqueConstraint('repository_id', 'repository_source_id', 'snapshot_sha256', name='uq_source_snapshots_hash')
    )
    op.create_table('import_sessions',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('principal_id', sa.Text(), nullable=False),
    sa.Column('source_type', sa.Text(), nullable=False),
    sa.Column('state', sa.Text(), server_default=sa.text("'created'"), nullable=False),
    sa.Column('staging_key', sa.Text(), nullable=True),
    sa.Column('preview_artifact_key', sa.Text(), nullable=True),
    sa.Column('policy_version', sa.Text(), nullable=False),
    sa.Column('source_fingerprint', sa.CHAR(length=64), nullable=True),
    sa.Column('upload_bytes', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('indexable_bytes', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('total_files', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('indexable_files', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('warnings', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('duplicate_candidates', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('limits', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('confirmed_repository_id', sa.Text(), nullable=True),
    sa.Column('confirmed_snapshot_id', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("id LIKE 'import_%%'", name=op.f('ck_import_sessions_id_prefix')),
    sa.CheckConstraint("jsonb_typeof(duplicate_candidates) = 'array'", name=op.f('ck_import_sessions_duplicate_candidates_array')),
    sa.CheckConstraint("jsonb_typeof(limits) = 'object'", name=op.f('ck_import_sessions_limits_object')),
    sa.CheckConstraint("jsonb_typeof(warnings) = 'array'", name=op.f('ck_import_sessions_warnings_array')),
    sa.CheckConstraint("source_fingerprint IS NULL OR (source_fingerprint ~ '^[0-9a-f]{64}$')", name=op.f('ck_import_sessions_source_fingerprint_sha256')),
    sa.CheckConstraint("source_type IN ('upload_zip','upload_folder','public_git')", name=op.f('ck_import_sessions_repository_sources_type')),
    sa.CheckConstraint("state IN ('created','acquiring','scanning','preview_ready','confirming','confirmed','cancelled','expired','failed')", name=op.f('ck_import_sessions_import_sessions_state')),
    sa.CheckConstraint('(confirmed_repository_id IS NULL) = (confirmed_snapshot_id IS NULL)', name=op.f('ck_import_sessions_confirmed_snapshot_pair')),
    sa.CheckConstraint('indexable_bytes >= 0', name=op.f('ck_import_sessions_indexable_bytes_nonnegative')),
    sa.CheckConstraint('indexable_files >= 0', name=op.f('ck_import_sessions_indexable_files_nonnegative')),
    sa.CheckConstraint('total_files >= 0', name=op.f('ck_import_sessions_total_files_nonnegative')),
    sa.CheckConstraint('upload_bytes >= 0', name=op.f('ck_import_sessions_upload_bytes_nonnegative')),
    sa.ForeignKeyConstraint(['confirmed_repository_id', 'confirmed_snapshot_id'], ['source_snapshots.repository_id', 'source_snapshots.id'], name='fk_import_sessions_confirmed_snapshot', ondelete='RESTRICT', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['principal_id'], ['operator_principals.id'], name=op.f('fk_import_sessions_principal_id_operator_principals'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_sessions'))
    )
    op.create_index('ix_import_sessions_expiry', 'import_sessions', ['state', 'expires_at', 'id'], unique=False, postgresql_where=sa.text("(state NOT IN ('confirmed', 'cancelled', 'expired', 'failed'))"))
    op.create_index('ix_import_sessions_principal_history', 'import_sessions', ['principal_id', sa.literal_column('created_at DESC'), sa.literal_column('id DESC')], unique=False)
    op.create_table('index_versions',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('repository_id', sa.Text(), nullable=False),
    sa.Column('version_number', sa.BigInteger(), nullable=False),
    sa.Column('source_snapshot_id', sa.Text(), nullable=False),
    sa.Column('base_index_version_id', sa.Text(), nullable=True),
    sa.Column('build_kind', sa.Text(), nullable=False),
    sa.Column('lifecycle', sa.Text(), server_default=sa.text("'building'"), nullable=False),
    sa.Column('manifest_schema_version', sa.Text(), nullable=False),
    sa.Column('producer_version', sa.Text(), nullable=False),
    sa.Column('configuration_sha256', sa.CHAR(length=64), nullable=False),
    sa.Column('manifest_storage_key', sa.Text(), nullable=True),
    sa.Column('manifest_sha256', sa.CHAR(length=64), nullable=True),
    sa.Column('validation_status', sa.Text(), nullable=True),
    sa.Column('critical_issue_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('coverage', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('superseded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("build_kind IN ('full','incremental')", name=op.f('ck_index_versions_build_kind')),
    sa.CheckConstraint("configuration_sha256 ~ '^[0-9a-f]{64}$'", name=op.f('ck_index_versions_configuration_sha256')),
    sa.CheckConstraint("id LIKE 'idx_%%'", name=op.f('ck_index_versions_id_prefix')),
    sa.CheckConstraint("lifecycle <> 'active' OR activated_at IS NOT NULL", name=op.f('ck_index_versions_active_timestamp')),
    sa.CheckConstraint("lifecycle IN ('building','validating','ready','ready_with_warnings','active','superseded','expired','failed','cancelled')", name=op.f('ck_index_versions_index_versions_lifecycle')),
    sa.CheckConstraint("lifecycle NOT IN ('ready','ready_with_warnings','active') OR (manifest_storage_key IS NOT NULL AND finished_at IS NOT NULL)", name=op.f('ck_index_versions_ready_manifest')),
    sa.CheckConstraint("manifest_sha256 IS NULL OR (manifest_sha256 ~ '^[0-9a-f]{64}$')", name=op.f('ck_index_versions_manifest_sha256')),
    sa.CheckConstraint("validation_status IS NULL OR validation_status IN ('passed','passed_with_warnings','failed')", name=op.f('ck_index_versions_validation_status')),
    sa.CheckConstraint('(manifest_storage_key IS NULL) = (manifest_sha256 IS NULL)', name=op.f('ck_index_versions_manifest_pair')),
    sa.CheckConstraint('critical_issue_count >= 0', name=op.f('ck_index_versions_critical_issue_count_nonnegative')),
    sa.CheckConstraint('version_number > 0', name=op.f('ck_index_versions_version_number_positive')),
    sa.ForeignKeyConstraint(['repository_id', 'base_index_version_id'], ['index_versions.repository_id', 'index_versions.id'], name='fk_index_versions_base', ondelete='RESTRICT', use_alter=True),
    sa.ForeignKeyConstraint(['repository_id', 'source_snapshot_id'], ['source_snapshots.repository_id', 'source_snapshots.id'], name='fk_index_versions_source_snapshot', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], name=op.f('fk_index_versions_repository_id_repositories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_index_versions')),
    sa.UniqueConstraint('repository_id', 'id', name='uq_index_versions_owner'),
    sa.UniqueConstraint('repository_id', 'version_number', name='uq_index_versions_number')
    )
    op.create_index('ix_index_versions_repository_history', 'index_versions', ['repository_id', sa.literal_column('version_number DESC'), 'id'], unique=False)
    op.create_index('uq_index_versions_one_active', 'index_versions', ['repository_id'], unique=True, postgresql_where=sa.text("lifecycle = 'active'"))
    op.create_table('evaluation_runs',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('dataset_id', sa.Text(), nullable=False),
    sa.Column('repository_id', sa.Text(), nullable=True),
    sa.Column('index_version_id', sa.Text(), nullable=True),
    sa.Column('method', sa.Text(), nullable=False),
    sa.Column('configuration_sha256', sa.CHAR(length=64), nullable=False),
    sa.Column('code_revision', sa.Text(), nullable=False),
    sa.Column('ranking_version', sa.Text(), nullable=True),
    sa.Column('workflow_version', sa.Text(), nullable=True),
    sa.Column('provider_identity', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('environment_identity', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('state', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("configuration_sha256 ~ '^[0-9a-f]{64}$'", name=op.f('ck_evaluation_runs_configuration_sha256')),
    sa.CheckConstraint("id LIKE 'evalrun_%%'", name=op.f('ck_evaluation_runs_id_prefix')),
    sa.CheckConstraint("state IN ('queued','running','succeeded','failed','cancelled')", name=op.f('ck_evaluation_runs_state')),
    sa.CheckConstraint('(repository_id IS NULL) = (index_version_id IS NULL)', name=op.f('ck_evaluation_runs_repository_version_pair')),
    sa.ForeignKeyConstraint(['dataset_id'], ['evaluation_datasets.id'], name=op.f('fk_evaluation_runs_dataset_id_evaluation_datasets'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['repository_id', 'index_version_id'], ['index_versions.repository_id', 'index_versions.id'], name='fk_evaluation_runs_version', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], name=op.f('fk_evaluation_runs_repository_id_repositories'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evaluation_runs'))
    )
    op.create_index('ix_evaluation_runs_recent', 'evaluation_runs', ['dataset_id', sa.literal_column('created_at DESC'), sa.literal_column('id DESC')], unique=False)
    op.create_table('files',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('repository_id', sa.Text(), nullable=False),
    sa.Column('index_version_id', sa.Text(), nullable=False),
    sa.Column('canonical_key', sa.Text(), nullable=False),
    sa.Column('relative_path', sa.Text(), nullable=False),
    sa.Column('language', sa.Text(), nullable=False),
    sa.Column('file_type', sa.Text(), nullable=False),
    sa.Column('byte_size', sa.BigInteger(), nullable=False),
    sa.Column('content_sha256', sa.CHAR(length=64), nullable=False),
    sa.Column('encoding', sa.Text(), nullable=False),
    sa.Column('parse_status', sa.Text(), nullable=False),
    sa.Column('producer_stage', sa.Text(), nullable=False),
    sa.Column('producer_name', sa.Text(), nullable=False),
    sa.Column('producer_version', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("content_sha256 ~ '^[0-9a-f]{64}$'", name=op.f('ck_files_content_sha256')),
    sa.CheckConstraint("id LIKE 'fileobs_%%'", name=op.f('ck_files_id_prefix')),
    sa.CheckConstraint("relative_path <> '' AND relative_path !~ '^/' AND relative_path !~ '(^|/)\\.\\.(/|$)' AND position(chr(92) in relative_path) = 0", name=op.f('ck_files_relative_path')),
    sa.CheckConstraint('byte_size >= 0', name=op.f('ck_files_byte_size_nonnegative')),
    sa.ForeignKeyConstraint(['repository_id', 'index_version_id'], ['index_versions.repository_id', 'index_versions.id'], name='fk_files_version', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_files')),
    sa.UniqueConstraint('repository_id', 'index_version_id', 'canonical_key', name='uq_files_canonical_key'),
    sa.UniqueConstraint('repository_id', 'index_version_id', 'id', name='uq_files_owner'),
    sa.UniqueConstraint('repository_id', 'index_version_id', 'relative_path', name='uq_files_relative_path')
    )
    op.create_index('ix_files_path', 'files', ['repository_id', 'index_version_id', 'relative_path', 'id'], unique=False)
    op.create_table('index_artifacts',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('repository_id', sa.Text(), nullable=False),
    sa.Column('index_version_id', sa.Text(), nullable=False),
    sa.Column('artifact_type', sa.Text(), nullable=False),
    sa.Column('storage_key', sa.Text(), nullable=False),
    sa.Column('schema_version', sa.Text(), nullable=False),
    sa.Column('sha256', sa.CHAR(length=64), nullable=False),
    sa.Column('byte_size', sa.BigInteger(), nullable=False),
    sa.Column('record_count', sa.BigInteger(), nullable=False),
    sa.Column('producer_stage', sa.Text(), nullable=False),
    sa.Column('producer_name', sa.Text(), nullable=False),
    sa.Column('producer_version', sa.Text(), nullable=False),
    sa.Column('required', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('retention_class', sa.Text(), nullable=False),
    sa.Column('finalized_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("id LIKE 'artifact_%%'", name=op.f('ck_index_artifacts_id_prefix')),
    sa.CheckConstraint("retention_class IN ('active_required','retained_previous_evidence','evaluation_audit','failed_build_diagnostic','temporary_debug')", name=op.f('ck_index_artifacts_retention_class')),
    sa.CheckConstraint("sha256 ~ '^[0-9a-f]{64}$'", name=op.f('ck_index_artifacts_sha256')),
    sa.CheckConstraint('byte_size >= 0', name=op.f('ck_index_artifacts_byte_size_nonnegative')),
    sa.CheckConstraint('record_count >= 0', name=op.f('ck_index_artifacts_record_count_nonnegative')),
    sa.ForeignKeyConstraint(['repository_id', 'index_version_id'], ['index_versions.repository_id', 'index_versions.id'], name='fk_index_artifacts_version', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_index_artifacts')),
    sa.UniqueConstraint('repository_id', 'index_version_id', 'artifact_type', 'storage_key', name='uq_index_artifacts_manifest_entry'),
    sa.UniqueConstraint('repository_id', 'index_version_id', 'id', name='uq_index_artifacts_owner'),
    sa.UniqueConstraint('storage_key', name=op.f('uq_index_artifacts_storage_key'))
    )
    op.create_index('ix_index_artifacts_manifest', 'index_artifacts', ['repository_id', 'index_version_id', 'artifact_type', 'id'], unique=False)
    op.create_table('index_jobs',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('repository_id', sa.Text(), nullable=False),
    sa.Column('source_snapshot_id', sa.Text(), nullable=False),
    sa.Column('requested_build_kind', sa.Text(), nullable=False),
    sa.Column('effective_build_kind', sa.Text(), nullable=False),
    sa.Column('base_index_version_id', sa.Text(), nullable=True),
    sa.Column('target_index_version_id', sa.Text(), nullable=True),
    sa.Column('state', sa.Text(), server_default=sa.text("'queued'"), nullable=False),
    sa.Column('priority', sa.SmallInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('idempotency_record_id', sa.Text(), nullable=False),
    sa.Column('current_attempt_id', sa.Text(), nullable=True),
    sa.Column('lease_generation', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('repository_generation', sa.BigInteger(), nullable=False),
    sa.Column('stage_code', sa.Text(), server_default=sa.text("'queued'"), nullable=False),
    sa.Column('progress_completed', sa.BigInteger(), nullable=True),
    sa.Column('progress_total', sa.BigInteger(), nullable=True),
    sa.Column('progress_unit', sa.Text(), nullable=True),
    sa.Column('cancellation_requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('warning_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('error_code', sa.Text(), nullable=True),
    sa.Column('error_message_safe', sa.Text(), nullable=True),
    sa.Column('queued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("effective_build_kind IN ('full','incremental')", name=op.f('ck_index_jobs_effective_build_kind')),
    sa.CheckConstraint("id LIKE 'job_%%'", name=op.f('ck_index_jobs_id_prefix')),
    sa.CheckConstraint("requested_build_kind IN ('full','incremental')", name=op.f('ck_index_jobs_requested_build_kind')),
    sa.CheckConstraint("state <> 'running' OR started_at IS NOT NULL", name=op.f('ck_index_jobs_running_started')),
    sa.CheckConstraint("state IN ('queued','running','succeeded','succeeded_with_warnings','failed','cancelled')", name=op.f('ck_index_jobs_index_jobs_state')),
    sa.CheckConstraint("state NOT IN ('succeeded','succeeded_with_warnings') OR target_index_version_id IS NOT NULL", name=op.f('ck_index_jobs_succeeded_target')),
    sa.CheckConstraint("state NOT IN ('succeeded','succeeded_with_warnings','failed','cancelled') OR finished_at IS NOT NULL", name=op.f('ck_index_jobs_terminal_finished')),
    sa.CheckConstraint('(progress_completed IS NULL) = (progress_total IS NULL)', name=op.f('ck_index_jobs_progress_pair')),
    sa.CheckConstraint('lease_generation >= 0', name=op.f('ck_index_jobs_lease_generation_nonnegative')),
    sa.CheckConstraint('progress_completed IS NOT NULL OR progress_unit IS NULL', name=op.f('ck_index_jobs_progress_unit_pair')),
    sa.CheckConstraint('progress_completed IS NULL OR (progress_completed >= 0 AND progress_total >= 0 AND progress_unit IS NOT NULL)', name=op.f('ck_index_jobs_progress_values')),
    sa.CheckConstraint('repository_generation >= 0', name=op.f('ck_index_jobs_repository_generation_nonnegative')),
    sa.CheckConstraint('warning_count >= 0', name=op.f('ck_index_jobs_warning_count_nonnegative')),
    sa.ForeignKeyConstraint(['idempotency_record_id'], ['idempotency_records.id'], name=op.f('fk_index_jobs_idempotency_record_id_idempotency_records'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['repository_id', 'base_index_version_id'], ['index_versions.repository_id', 'index_versions.id'], name='fk_index_jobs_base_version', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['repository_id', 'id', 'current_attempt_id'], ['job_attempts.repository_id', 'job_attempts.job_id', 'job_attempts.id'], name='fk_index_jobs_current_attempt', ondelete='RESTRICT', initially='DEFERRED', deferrable=True, use_alter=True),
    sa.ForeignKeyConstraint(['repository_id', 'source_snapshot_id'], ['source_snapshots.repository_id', 'source_snapshots.id'], name='fk_index_jobs_source_snapshot', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['repository_id', 'target_index_version_id'], ['index_versions.repository_id', 'index_versions.id'], name='fk_index_jobs_target_version', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], name=op.f('fk_index_jobs_repository_id_repositories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_index_jobs')),
    sa.UniqueConstraint('idempotency_record_id', name=op.f('uq_index_jobs_idempotency_record_id')),
    sa.UniqueConstraint('repository_id', 'id', name='uq_index_jobs_owner')
    )
    op.create_index('ix_index_jobs_recovery', 'index_jobs', ['state', 'updated_at', 'id'], unique=False, postgresql_where=sa.text("state IN ('queued', 'running')"))
    op.create_index('ix_index_jobs_repository_history', 'index_jobs', ['repository_id', sa.literal_column('created_at DESC'), sa.literal_column('id DESC')], unique=False)
    op.create_index('uq_index_jobs_one_active', 'index_jobs', ['repository_id'], unique=True, postgresql_where=sa.text("state IN ('queued', 'running')"))
    op.create_table('messages',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('conversation_id', sa.Text(), nullable=False),
    sa.Column('repository_id', sa.Text(), nullable=False),
    sa.Column('index_version_id', sa.Text(), nullable=True),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('assistant_outcome', sa.Text(), nullable=True),
    sa.Column('request_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("assistant_outcome IS NULL OR assistant_outcome IN ('answered','limited','insufficient_evidence','cancelled','failed')", name=op.f('ck_messages_assistant_outcome')),
    sa.CheckConstraint("id LIKE 'message_%%'", name=op.f('ck_messages_id_prefix')),
    sa.CheckConstraint("role IN ('operator','assistant','system')", name=op.f('ck_messages_message_role')),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_messages_conversation_id_conversations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repository_id', 'index_version_id'], ['index_versions.repository_id', 'index_versions.id'], name='fk_messages_version', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], name=op.f('fk_messages_repository_id_repositories'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages')),
    sa.UniqueConstraint('conversation_id', 'id', name='uq_messages_conversation'),
    sa.UniqueConstraint('repository_id', 'index_version_id', 'id', name='uq_messages_owner')
    )
    op.create_index('ix_messages_order', 'messages', ['conversation_id', 'created_at', 'id'], unique=False)
    op.create_table('validation_issues',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('repository_id', sa.Text(), nullable=False),
    sa.Column('index_version_id', sa.Text(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('severity', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.Text(), nullable=True),
    sa.Column('entity_key', sa.Text(), nullable=True),
    sa.Column('file_key', sa.Text(), nullable=True),
    sa.Column('start_line', sa.Integer(), nullable=True),
    sa.Column('end_line', sa.Integer(), nullable=True),
    sa.Column('message_safe', sa.Text(), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("id LIKE 'issue_%%'", name=op.f('ck_validation_issues_id_prefix')),
    sa.CheckConstraint("severity IN ('info','warning','error','critical')", name=op.f('ck_validation_issues_severity')),
    sa.CheckConstraint('(start_line IS NULL AND end_line IS NULL) OR (start_line > 0 AND end_line >= start_line)', name=op.f('ck_validation_issues_source_range')),
    sa.ForeignKeyConstraint(['repository_id', 'index_version_id'], ['index_versions.repository_id', 'index_versions.id'], name='fk_validation_issues_version', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_validation_issues'))
    )
    op.create_index('ix_validation_issues_version_severity', 'validation_issues', ['repository_id', 'index_version_id', 'severity', 'id'], unique=False)
    op.create_table('agent_traces',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('principal_id', sa.Text(), nullable=False),
    sa.Column('repository_id', sa.Text(), nullable=False),
    sa.Column('index_version_id', sa.Text(), nullable=True),
    sa.Column('conversation_id', sa.Text(), nullable=True),
    sa.Column('request_message_id', sa.Text(), nullable=True),
    sa.Column('response_message_id', sa.Text(), nullable=True),
    sa.Column('workflow_version', sa.Text(), nullable=False),
    sa.Column('outcome', sa.Text(), nullable=False),
    sa.Column('budget_summary', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('provider_summary', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("id LIKE 'trace_%%'", name=op.f('ck_agent_traces_id_prefix')),
    sa.CheckConstraint("outcome IN ('answered','limited','insufficient_evidence','cancelled','failed')", name=op.f('ck_agent_traces_assistant_outcome')),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_agent_traces_conversation_id_conversations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['principal_id'], ['operator_principals.id'], name=op.f('fk_agent_traces_principal_id_operator_principals'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['repository_id', 'index_version_id'], ['index_versions.repository_id', 'index_versions.id'], name='fk_agent_traces_version', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['request_message_id'], ['messages.id'], name=op.f('fk_agent_traces_request_message_id_messages'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['response_message_id'], ['messages.id'], name=op.f('fk_agent_traces_response_message_id_messages'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_traces'))
    )
    op.create_table('capability_readiness',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('repository_id', sa.Text(), nullable=False),
    sa.Column('index_version_id', sa.Text(), nullable=False),
    sa.Column('capability', sa.Text(), nullable=False),
    sa.Column('state', sa.Text(), nullable=False),
    sa.Column('reason_codes', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('required_artifact_types', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('validation_issue_id', sa.Text(), nullable=True),
    sa.Column('coverage', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('remediation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("id LIKE 'capability_%%'", name=op.f('ck_capability_readiness_id_prefix')),
    sa.CheckConstraint("jsonb_typeof(reason_codes) = 'array'", name=op.f('ck_capability_readiness_reason_codes_array')),
    sa.CheckConstraint("jsonb_typeof(required_artifact_types) = 'array'", name=op.f('ck_capability_readiness_required_artifact_types_array')),
    sa.CheckConstraint("state IN ('ready','limited','unavailable','failed','stale')", name=op.f('ck_capability_readiness_capability_state')),
    sa.ForeignKeyConstraint(['repository_id', 'index_version_id'], ['index_versions.repository_id', 'index_versions.id'], name='fk_capability_readiness_version', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['validation_issue_id'], ['validation_issues.id'], name=op.f('fk_capability_readiness_validation_issue_id_validation_issues'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_capability_readiness')),
    sa.UniqueConstraint('repository_id', 'index_version_id', 'capability', name='uq_capability_readiness_capability')
    )
    op.create_table('chunks',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('repository_id', sa.Text(), nullable=False),
    sa.Column('index_version_id', sa.Text(), nullable=False),
    sa.Column('canonical_key', sa.Text(), nullable=False),
    sa.Column('source_entity_type', sa.Text(), nullable=False),
    sa.Column('source_canonical_key', sa.Text(), nullable=False),
    sa.Column('file_id', sa.Text(), nullable=False),
    sa.Column('chunk_kind', sa.Text(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('start_line', sa.Integer(), nullable=False),
    sa.Column('end_line', sa.Integer(), nullable=False),
    sa.Column('content_sha256', sa.CHAR(length=64), nullable=False),
    sa.Column('safe_preview', sa.Text(), nullable=False),
    sa.Column('artifact_id', sa.Text(), nullable=True),
    sa.Column('artifact_offset', sa.BigInteger(), nullable=True),
    sa.Column('artifact_length', sa.BigInteger(), nullable=True),
    sa.Column('retrieval_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('producer_stage', sa.Text(), nullable=False),
    sa.Column('producer_name', sa.Text(), nullable=False),
    sa.Column('producer_version', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("content_sha256 ~ '^[0-9a-f]{64}$'", name=op.f('ck_chunks_content_sha256')),
    sa.CheckConstraint("id LIKE 'chunkobs_%%'", name=op.f('ck_chunks_id_prefix')),
    sa.CheckConstraint('(artifact_id IS NULL AND artifact_offset IS NULL AND artifact_length IS NULL) OR (artifact_id IS NOT NULL AND artifact_offset >= 0 AND artifact_length >= 0)', name=op.f('ck_chunks_artifact_location')),
    sa.CheckConstraint('ordinal >= 0', name=op.f('ck_chunks_ordinal_nonnegative')),
    sa.CheckConstraint('start_line > 0 AND end_line >= start_line', name=op.f('ck_chunks_source_range')),
    sa.ForeignKeyConstraint(['repository_id', 'index_version_id', 'artifact_id'], ['index_artifacts.repository_id', 'index_artifacts.index_version_id', 'index_artifacts.id'], name='fk_chunks_artifact', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['repository_id', 'index_version_id', 'file_id'], ['files.repository_id', 'files.index_version_id', 'files.id'], name='fk_chunks_file', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repository_id', 'index_version_id'], ['index_versions.repository_id', 'index_versions.id'], name='fk_chunks_version', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chunks')),
    sa.UniqueConstraint('repository_id', 'index_version_id', 'canonical_key', name='uq_chunks_canonical_key')
    )
    op.create_index('ix_chunks_source', 'chunks', ['repository_id', 'index_version_id', 'source_canonical_key', 'ordinal', 'id'], unique=False)
    op.create_table('claims',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('message_id', sa.Text(), nullable=False),
    sa.Column('repository_id', sa.Text(), nullable=False),
    sa.Column('index_version_id', sa.Text(), nullable=False),
    sa.Column('claim_text', sa.Text(), nullable=False),
    sa.Column('support_level', sa.Text(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("id LIKE 'claim_%%'", name=op.f('ck_claims_id_prefix')),
    sa.CheckConstraint("support_level IN ('supported','qualified','unsupported')", name=op.f('ck_claims_support_level')),
    sa.CheckConstraint('ordinal >= 0', name=op.f('ck_claims_ordinal_nonnegative')),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('fk_claims_message_id_messages'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repository_id', 'index_version_id', 'message_id'], ['messages.repository_id', 'messages.index_version_id', 'messages.id'], name='fk_claims_message_owner', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_claims')),
    sa.UniqueConstraint('message_id', 'ordinal', name='uq_claims_ordinal'),
    sa.UniqueConstraint('repository_id', 'index_version_id', 'id', name='uq_claims_owner')
    )
    op.create_table('evidence',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('repository_id', sa.Text(), nullable=False),
    sa.Column('index_version_id', sa.Text(), nullable=False),
    sa.Column('source_entity_type', sa.Text(), nullable=False),
    sa.Column('source_canonical_key', sa.Text(), nullable=False),
    sa.Column('file_id', sa.Text(), nullable=True),
    sa.Column('start_line', sa.Integer(), nullable=True),
    sa.Column('end_line', sa.Integer(), nullable=True),
    sa.Column('content_sha256', sa.CHAR(length=64), nullable=False),
    sa.Column('support_type', sa.Text(), nullable=False),
    sa.Column('producer_stage', sa.Text(), nullable=False),
    sa.Column('producer_name', sa.Text(), nullable=False),
    sa.Column('producer_version', sa.Text(), nullable=False),
    sa.Column('retrieval_source', sa.Text(), nullable=False),
    sa.Column('selection_reason', sa.Text(), nullable=False),
    sa.Column('freshness', sa.Text(), server_default=sa.text("'fresh'"), nullable=False),
    sa.Column('safe_preview', sa.Text(), nullable=False),
    sa.Column('validation_details', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('staled_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("content_sha256 ~ '^[0-9a-f]{64}$'", name=op.f('ck_evidence_content_sha256')),
    sa.CheckConstraint("freshness IN ('fresh','stale','invalid')", name=op.f('ck_evidence_evidence_freshness')),
    sa.CheckConstraint("id LIKE 'evidence_%%'", name=op.f('ck_evidence_id_prefix')),
    sa.CheckConstraint("support_type IN ('source_exact','static_resolved','static_ambiguous','heuristic_inferred','llm_inferred','user_supplied')", name=op.f('ck_evidence_support_type')),
    sa.CheckConstraint('(start_line IS NULL AND end_line IS NULL) OR (start_line > 0 AND end_line >= start_line)', name=op.f('ck_evidence_source_range')),
    sa.ForeignKeyConstraint(['repository_id', 'index_version_id', 'file_id'], ['files.repository_id', 'files.index_version_id', 'files.id'], name='fk_evidence_file', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['repository_id', 'index_version_id'], ['index_versions.repository_id', 'index_versions.id'], name='fk_evidence_version', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence')),
    sa.UniqueConstraint('repository_id', 'index_version_id', 'id', name='uq_evidence_owner')
    )
    op.create_index('ix_evidence_source', 'evidence', ['repository_id', 'index_version_id', 'source_canonical_key', sa.literal_column('created_at DESC'), 'id'], unique=False)
    op.create_table('graph_candidates',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('repository_id', sa.Text(), nullable=False),
    sa.Column('index_version_id', sa.Text(), nullable=False),
    sa.Column('canonical_key', sa.Text(), nullable=False),
    sa.Column('candidate_kind', sa.Text(), nullable=False),
    sa.Column('source_canonical_key', sa.Text(), nullable=True),
    sa.Column('target_canonical_key', sa.Text(), nullable=True),
    sa.Column('relation_type', sa.Text(), nullable=True),
    sa.Column('origin', sa.Text(), nullable=False),
    sa.Column('file_id', sa.Text(), nullable=True),
    sa.Column('start_line', sa.Integer(), nullable=True),
    sa.Column('end_line', sa.Integer(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('normalization_reason', sa.Text(), nullable=True),
    sa.Column('producer_stage', sa.Text(), nullable=False),
    sa.Column('producer_name', sa.Text(), nullable=False),
    sa.Column('producer_version', sa.Text(), nullable=False),
    sa.Column('support_type', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('diagnostic_ids', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(candidate_kind = 'edge' AND source_canonical_key IS NOT NULL AND target_canonical_key IS NOT NULL AND relation_type IS NOT NULL) OR (candidate_kind = 'node' AND target_canonical_key IS NULL)", name=op.f('ck_graph_candidates_candidate_shape')),
    sa.CheckConstraint("candidate_kind IN ('node','edge')", name=op.f('ck_graph_candidates_candidate_kind')),
    sa.CheckConstraint("id LIKE 'candidate_%%'", name=op.f('ck_graph_candidates_id_prefix')),
    sa.CheckConstraint("jsonb_typeof(diagnostic_ids) = 'array'", name=op.f('ck_graph_candidates_diagnostic_ids_array')),
    sa.CheckConstraint("status IN ('pending','accepted','changed','dropped')", name=op.f('ck_graph_candidates_status')),
    sa.CheckConstraint('(start_line IS NULL AND end_line IS NULL) OR (start_line > 0 AND end_line >= start_line)', name=op.f('ck_graph_candidates_source_range')),
    sa.CheckConstraint('confidence IS NULL OR (confidence >= 0 AND confidence <= 1)', name=op.f('ck_graph_candidates_confidence_range')),
    sa.ForeignKeyConstraint(['repository_id', 'index_version_id', 'file_id'], ['files.repository_id', 'files.index_version_id', 'files.id'], name='fk_graph_candidates_file', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['repository_id', 'index_version_id'], ['index_versions.repository_id', 'index_versions.id'], name='fk_graph_candidates_version', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_graph_candidates')),
    sa.UniqueConstraint('repository_id', 'index_version_id', 'canonical_key', name='uq_graph_candidates_canonical_key')
    )
    op.create_table('graph_nodes',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('repository_id', sa.Text(), nullable=False),
    sa.Column('index_version_id', sa.Text(), nullable=False),
    sa.Column('canonical_key', sa.Text(), nullable=False),
    sa.Column('node_type', sa.Text(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('file_id', sa.Text(), nullable=True),
    sa.Column('entity_canonical_key', sa.Text(), nullable=True),
    sa.Column('start_line', sa.Integer(), nullable=True),
    sa.Column('end_line', sa.Integer(), nullable=True),
    sa.Column('coverage_state', sa.Text(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('producer_stage', sa.Text(), nullable=False),
    sa.Column('producer_name', sa.Text(), nullable=False),
    sa.Column('producer_version', sa.Text(), nullable=False),
    sa.Column('support_type', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('diagnostic_ids', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("id LIKE 'nodeobs_%%'", name=op.f('ck_graph_nodes_id_prefix')),
    sa.CheckConstraint("jsonb_typeof(diagnostic_ids) = 'array'", name=op.f('ck_graph_nodes_diagnostic_ids_array')),
    sa.CheckConstraint('(start_line IS NULL AND end_line IS NULL) OR (start_line > 0 AND end_line >= start_line)', name=op.f('ck_graph_nodes_source_range')),
    sa.CheckConstraint('confidence IS NULL OR (confidence >= 0 AND confidence <= 1)', name=op.f('ck_graph_nodes_confidence_range')),
    sa.ForeignKeyConstraint(['repository_id', 'index_version_id', 'file_id'], ['files.repository_id', 'files.index_version_id', 'files.id'], name='fk_graph_nodes_file', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['repository_id', 'index_version_id'], ['index_versions.repository_id', 'index_versions.id'], name='fk_graph_nodes_version', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_graph_nodes')),
    sa.UniqueConstraint('repository_id', 'index_version_id', 'canonical_key', name='uq_graph_nodes_canonical_key'),
    sa.UniqueConstraint('repository_id', 'index_version_id', 'id', name='uq_graph_nodes_owner')
    )
    op.create_table('job_attempts',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('job_id', sa.Text(), nullable=False),
    sa.Column('repository_id', sa.Text(), nullable=False),
    sa.Column('lease_generation', sa.BigInteger(), nullable=False),
    sa.Column('worker_id', sa.Text(), nullable=False),
    sa.Column('state', sa.Text(), server_default=sa.text("'claimed'"), nullable=False),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('checkpoint_stage', sa.Text(), nullable=True),
    sa.Column('checkpoint_artifact_id', sa.Text(), nullable=True),
    sa.Column('error_code', sa.Text(), nullable=True),
    sa.Column('error_message_safe', sa.Text(), nullable=True),
    sa.Column('claimed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("id LIKE 'attempt_%%'", name=op.f('ck_job_attempts_id_prefix')),
    sa.CheckConstraint("state IN ('claimed','running','succeeded','failed','cancelled','lease_lost')", name=op.f('ck_job_attempts_job_attempts_state')),
    sa.CheckConstraint('lease_generation > 0', name=op.f('ck_job_attempts_lease_generation_positive')),
    sa.ForeignKeyConstraint(['checkpoint_artifact_id'], ['index_artifacts.id'], name=op.f('fk_job_attempts_checkpoint_artifact_id_index_artifacts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['repository_id', 'job_id'], ['index_jobs.repository_id', 'index_jobs.id'], name='fk_job_attempts_job', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_attempts')),
    sa.UniqueConstraint('job_id', 'id', name='uq_job_attempts_job'),
    sa.UniqueConstraint('job_id', 'lease_generation', name='uq_job_attempts_generation'),
    sa.UniqueConstraint('repository_id', 'job_id', 'id', name='uq_job_attempts_owner')
    )
    op.create_index('ix_job_attempts_stale_lease', 'job_attempts', ['state', 'lease_expires_at', 'id'], unique=False, postgresql_where=sa.text("state IN ('claimed', 'running')"))
    op.create_table('symbols',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('repository_id', sa.Text(), nullable=False),
    sa.Column('index_version_id', sa.Text(), nullable=False),
    sa.Column('canonical_key', sa.Text(), nullable=False),
    sa.Column('file_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('qualified_name', sa.Text(), nullable=False),
    sa.Column('symbol_kind', sa.Text(), nullable=False),
    sa.Column('signature', sa.Text(), nullable=True),
    sa.Column('start_line', sa.Integer(), nullable=False),
    sa.Column('end_line', sa.Integer(), nullable=False),
    sa.Column('producer_stage', sa.Text(), nullable=False),
    sa.Column('producer_name', sa.Text(), nullable=False),
    sa.Column('producer_version', sa.Text(), nullable=False),
    sa.Column('support_type', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('diagnostic_ids', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("id LIKE 'symbolobs_%%'", name=op.f('ck_symbols_id_prefix')),
    sa.CheckConstraint("jsonb_typeof(diagnostic_ids) = 'array'", name=op.f('ck_symbols_diagnostic_ids_array')),
    sa.CheckConstraint('confidence IS NULL OR (confidence >= 0 AND confidence <= 1)', name=op.f('ck_symbols_confidence_range')),
    sa.CheckConstraint('start_line > 0 AND end_line >= start_line', name=op.f('ck_symbols_source_range')),
    sa.ForeignKeyConstraint(['repository_id', 'index_version_id', 'file_id'], ['files.repository_id', 'files.index_version_id', 'files.id'], name='fk_symbols_file', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repository_id', 'index_version_id'], ['index_versions.repository_id', 'index_versions.id'], name='fk_symbols_version', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_symbols')),
    sa.UniqueConstraint('repository_id', 'index_version_id', 'canonical_key', name='uq_symbols_canonical_key'),
    sa.UniqueConstraint('repository_id', 'index_version_id', 'id', name='uq_symbols_owner')
    )
    op.create_index('ix_symbols_name', 'symbols', ['repository_id', 'index_version_id', 'name', 'canonical_key', 'id'], unique=False)
    op.create_table('agent_trace_events',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('trace_id', sa.Text(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('tool_name', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('duration_ms', sa.BigInteger(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("id LIKE 'traceevent_%%'", name=op.f('ck_agent_trace_events_id_prefix')),
    sa.CheckConstraint('duration_ms IS NULL OR duration_ms >= 0', name=op.f('ck_agent_trace_events_duration_ms_nonnegative')),
    sa.CheckConstraint('sequence > 0', name=op.f('ck_agent_trace_events_sequence_positive')),
    sa.ForeignKeyConstraint(['trace_id'], ['agent_traces.id'], name=op.f('fk_agent_trace_events_trace_id_agent_traces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_trace_events')),
    sa.UniqueConstraint('trace_id', 'sequence', name='uq_agent_trace_events_sequence')
    )
    op.create_index('ix_trace_events_order', 'agent_trace_events', ['trace_id', 'sequence', 'id'], unique=False)
    op.create_table('citations',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('claim_id', sa.Text(), nullable=False),
    sa.Column('evidence_id', sa.Text(), nullable=False),
    sa.Column('repository_id', sa.Text(), nullable=False),
    sa.Column('index_version_id', sa.Text(), nullable=False),
    sa.Column('display_locator', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("id LIKE 'citation_%%'", name=op.f('ck_citations_id_prefix')),
    sa.ForeignKeyConstraint(['repository_id', 'index_version_id', 'claim_id'], ['claims.repository_id', 'claims.index_version_id', 'claims.id'], name='fk_citations_claim', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repository_id', 'index_version_id', 'evidence_id'], ['evidence.repository_id', 'evidence.index_version_id', 'evidence.id'], name='fk_citations_evidence', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_citations')),
    sa.UniqueConstraint('claim_id', 'evidence_id', name='uq_citations_claim_evidence')
    )
    op.create_table('endpoints',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('repository_id', sa.Text(), nullable=False),
    sa.Column('index_version_id', sa.Text(), nullable=False),
    sa.Column('canonical_key', sa.Text(), nullable=False),
    sa.Column('file_id', sa.Text(), nullable=False),
    sa.Column('handler_symbol_id', sa.Text(), nullable=True),
    sa.Column('protocol', sa.Text(), nullable=False),
    sa.Column('method', sa.Text(), nullable=False),
    sa.Column('normalized_route', sa.Text(), nullable=False),
    sa.Column('start_line', sa.Integer(), nullable=False),
    sa.Column('end_line', sa.Integer(), nullable=False),
    sa.Column('producer_stage', sa.Text(), nullable=False),
    sa.Column('producer_name', sa.Text(), nullable=False),
    sa.Column('producer_version', sa.Text(), nullable=False),
    sa.Column('support_type', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('diagnostic_ids', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("id LIKE 'endpointobs_%%'", name=op.f('ck_endpoints_id_prefix')),
    sa.CheckConstraint("jsonb_typeof(diagnostic_ids) = 'array'", name=op.f('ck_endpoints_diagnostic_ids_array')),
    sa.CheckConstraint('confidence IS NULL OR (confidence >= 0 AND confidence <= 1)', name=op.f('ck_endpoints_confidence_range')),
    sa.CheckConstraint('start_line > 0 AND end_line >= start_line', name=op.f('ck_endpoints_source_range')),
    sa.ForeignKeyConstraint(['repository_id', 'index_version_id', 'file_id'], ['files.repository_id', 'files.index_version_id', 'files.id'], name='fk_endpoints_file', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repository_id', 'index_version_id', 'handler_symbol_id'], ['symbols.repository_id', 'symbols.index_version_id', 'symbols.id'], name='fk_endpoints_handler', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['repository_id', 'index_version_id'], ['index_versions.repository_id', 'index_versions.id'], name='fk_endpoints_version', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_endpoints')),
    sa.UniqueConstraint('repository_id', 'index_version_id', 'canonical_key', name='uq_endpoints_canonical_key'),
    sa.UniqueConstraint('repository_id', 'index_version_id', 'protocol', 'method', 'normalized_route', 'handler_symbol_id', name='uq_endpoints_route_handler')
    )
    op.create_index('ix_endpoints_route', 'endpoints', ['repository_id', 'index_version_id', 'protocol', 'method', 'normalized_route', 'id'], unique=False)
    op.create_table('evaluation_results',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('run_id', sa.Text(), nullable=False),
    sa.Column('case_id', sa.Text(), nullable=False),
    sa.Column('trace_id', sa.Text(), nullable=True),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('outcome', sa.Text(), nullable=False),
    sa.Column('retrieved_evidence', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('citations', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('automatic_metrics', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('manual_scores', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('duration_ms', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("id LIKE 'evalresult_%%'", name=op.f('ck_evaluation_results_id_prefix')),
    sa.CheckConstraint('duration_ms IS NULL OR duration_ms >= 0', name=op.f('ck_evaluation_results_duration_ms_nonnegative')),
    sa.ForeignKeyConstraint(['case_id'], ['evaluation_cases.id'], name=op.f('fk_evaluation_results_case_id_evaluation_cases'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['run_id'], ['evaluation_runs.id'], name=op.f('fk_evaluation_results_run_id_evaluation_runs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trace_id'], ['agent_traces.id'], name=op.f('fk_evaluation_results_trace_id_agent_traces'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evaluation_results')),
    sa.UniqueConstraint('run_id', 'case_id', name='uq_evaluation_results_case')
    )
    op.create_index('ix_evaluation_results_run', 'evaluation_results', ['run_id', 'case_id', 'id'], unique=False)
    op.create_table('graph_edges',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('repository_id', sa.Text(), nullable=False),
    sa.Column('index_version_id', sa.Text(), nullable=False),
    sa.Column('canonical_key', sa.Text(), nullable=False),
    sa.Column('source_node_id', sa.Text(), nullable=False),
    sa.Column('target_node_id', sa.Text(), nullable=False),
    sa.Column('edge_type', sa.Text(), nullable=False),
    sa.Column('file_id', sa.Text(), nullable=True),
    sa.Column('start_line', sa.Integer(), nullable=True),
    sa.Column('end_line', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('producer_stage', sa.Text(), nullable=False),
    sa.Column('producer_name', sa.Text(), nullable=False),
    sa.Column('producer_version', sa.Text(), nullable=False),
    sa.Column('support_type', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('diagnostic_ids', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("id LIKE 'edgeobs_%%'", name=op.f('ck_graph_edges_id_prefix')),
    sa.CheckConstraint("jsonb_typeof(diagnostic_ids) = 'array'", name=op.f('ck_graph_edges_diagnostic_ids_array')),
    sa.CheckConstraint('(start_line IS NULL AND end_line IS NULL) OR (start_line > 0 AND end_line >= start_line)', name=op.f('ck_graph_edges_source_range')),
    sa.CheckConstraint('confidence IS NULL OR (confidence >= 0 AND confidence <= 1)', name=op.f('ck_graph_edges_confidence_range')),
    sa.ForeignKeyConstraint(['repository_id', 'index_version_id', 'file_id'], ['files.repository_id', 'files.index_version_id', 'files.id'], name='fk_graph_edges_file', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['repository_id', 'index_version_id', 'source_node_id'], ['graph_nodes.repository_id', 'graph_nodes.index_version_id', 'graph_nodes.id'], name='fk_graph_edges_source', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repository_id', 'index_version_id', 'target_node_id'], ['graph_nodes.repository_id', 'graph_nodes.index_version_id', 'graph_nodes.id'], name='fk_graph_edges_target', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repository_id', 'index_version_id'], ['index_versions.repository_id', 'index_versions.id'], name='fk_graph_edges_version', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_graph_edges')),
    sa.UniqueConstraint('repository_id', 'index_version_id', 'canonical_key', name='uq_graph_edges_canonical_key')
    )
    op.create_index('ix_graph_edges_forward', 'graph_edges', ['repository_id', 'index_version_id', 'source_node_id', 'edge_type', 'target_node_id', 'id'], unique=False)
    op.create_index('ix_graph_edges_reverse', 'graph_edges', ['repository_id', 'index_version_id', 'target_node_id', 'edge_type', 'source_node_id', 'id'], unique=False)
    op.create_table('references',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('repository_id', sa.Text(), nullable=False),
    sa.Column('index_version_id', sa.Text(), nullable=False),
    sa.Column('canonical_key', sa.Text(), nullable=False),
    sa.Column('source_file_id', sa.Text(), nullable=False),
    sa.Column('source_symbol_id', sa.Text(), nullable=True),
    sa.Column('source_canonical_key', sa.Text(), nullable=False),
    sa.Column('target_entity_type', sa.Text(), nullable=True),
    sa.Column('target_canonical_key', sa.Text(), nullable=True),
    sa.Column('reference_type', sa.Text(), nullable=False),
    sa.Column('outcome', sa.Text(), nullable=False),
    sa.Column('start_line', sa.Integer(), nullable=False),
    sa.Column('end_line', sa.Integer(), nullable=False),
    sa.Column('candidate_keys', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('producer_stage', sa.Text(), nullable=False),
    sa.Column('producer_name', sa.Text(), nullable=False),
    sa.Column('producer_version', sa.Text(), nullable=False),
    sa.Column('support_type', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('diagnostic_ids', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(outcome = 'resolved' AND target_canonical_key IS NOT NULL) OR (outcome = 'unresolved' AND target_canonical_key IS NULL) OR (outcome = 'ambiguous' AND target_canonical_key IS NULL AND jsonb_array_length(candidate_keys) >= 2)", name=op.f('ck_references_outcome_target')),
    sa.CheckConstraint("id LIKE 'reference_%%'", name=op.f('ck_references_id_prefix')),
    sa.CheckConstraint("jsonb_typeof(candidate_keys) = 'array'", name=op.f('ck_references_candidate_keys_array')),
    sa.CheckConstraint("jsonb_typeof(diagnostic_ids) = 'array'", name=op.f('ck_references_diagnostic_ids_array')),
    sa.CheckConstraint("outcome IN ('resolved','ambiguous','unresolved')", name=op.f('ck_references_reference_outcome')),
    sa.CheckConstraint('confidence IS NULL OR (confidence >= 0 AND confidence <= 1)', name=op.f('ck_references_confidence_range')),
    sa.CheckConstraint('start_line > 0 AND end_line >= start_line', name=op.f('ck_references_source_range')),
    sa.ForeignKeyConstraint(['repository_id', 'index_version_id', 'source_file_id'], ['files.repository_id', 'files.index_version_id', 'files.id'], name='fk_references_file', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repository_id', 'index_version_id', 'source_symbol_id'], ['symbols.repository_id', 'symbols.index_version_id', 'symbols.id'], name='fk_references_symbol', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['repository_id', 'index_version_id'], ['index_versions.repository_id', 'index_versions.id'], name='fk_references_version', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_references')),
    sa.UniqueConstraint('repository_id', 'index_version_id', 'canonical_key', name='uq_references_canonical_key')
    )
    op.create_index('ix_references_source', 'references', ['repository_id', 'index_version_id', 'source_canonical_key', 'reference_type', 'id'], unique=False)
    op.create_index('ix_references_target', 'references', ['repository_id', 'index_version_id', 'target_canonical_key', 'reference_type', 'id'], unique=False)
    op.create_foreign_key(
        'fk_repositories_active_version', 'repositories', 'index_versions',
        ['id', 'active_index_version_id'], ['repository_id', 'id'],
        ondelete='RESTRICT', deferrable=True, initially='DEFERRED',
    )
    op.create_foreign_key(
        'fk_index_jobs_current_attempt', 'index_jobs', 'job_attempts',
        ['repository_id', 'id', 'current_attempt_id'], ['repository_id', 'job_id', 'id'],
        ondelete='RESTRICT', deferrable=True, initially='DEFERRED',
    )
    op.create_foreign_key(
        'fk_index_versions_base', 'index_versions', 'index_versions',
        ['repository_id', 'base_index_version_id'], ['repository_id', 'id'],
        ondelete='RESTRICT',
    )
    op.execute("""
        CREATE FUNCTION enforce_repository_active_version() RETURNS trigger
        LANGUAGE plpgsql AS $$
        BEGIN
          IF NEW.active_index_version_id IS NOT NULL AND NOT EXISTS (
            SELECT 1 FROM index_versions v
             WHERE v.repository_id = NEW.id
               AND v.id = NEW.active_index_version_id
               AND v.lifecycle = 'active'
          ) THEN
            RAISE EXCEPTION 'repository active version must have active lifecycle';
          END IF;
          RETURN NEW;
        END
        $$;
        CREATE CONSTRAINT TRIGGER trg_repositories_active_version
          AFTER INSERT OR UPDATE OF active_index_version_id ON repositories
          DEFERRABLE INITIALLY DEFERRED
          FOR EACH ROW EXECUTE FUNCTION enforce_repository_active_version();
    """)
    op.execute("""
        CREATE FUNCTION protect_active_index_version() RETURNS trigger
        LANGUAGE plpgsql AS $$
        BEGIN
          IF NEW.lifecycle <> 'active' AND EXISTS (
            SELECT 1 FROM repositories r
             WHERE r.id = NEW.repository_id AND r.active_index_version_id = NEW.id
          ) THEN
            RAISE EXCEPTION 'referenced active version must retain active lifecycle';
          END IF;
          RETURN NEW;
        END
        $$;
        CREATE CONSTRAINT TRIGGER trg_index_versions_active_lifecycle
          AFTER UPDATE OF lifecycle ON index_versions
          DEFERRABLE INITIALLY DEFERRED
          FOR EACH ROW EXECUTE FUNCTION protect_active_index_version();
    """)
    op.execute("""
        CREATE FUNCTION reject_audit_event_mutation() RETURNS trigger
        LANGUAGE plpgsql AS $$
        BEGIN
          RAISE EXCEPTION 'audit_events is append-only';
        END
        $$;
        CREATE TRIGGER trg_audit_events_append_only
          BEFORE UPDATE OR DELETE ON audit_events
          FOR EACH ROW EXECUTE FUNCTION reject_audit_event_mutation();
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP TRIGGER trg_audit_events_append_only ON audit_events')
    op.execute('DROP FUNCTION reject_audit_event_mutation()')
    op.execute('DROP TRIGGER trg_index_versions_active_lifecycle ON index_versions')
    op.execute('DROP FUNCTION protect_active_index_version()')
    op.execute('DROP TRIGGER trg_repositories_active_version ON repositories')
    op.execute('DROP FUNCTION enforce_repository_active_version()')
    op.drop_constraint('fk_index_versions_base', 'index_versions', type_='foreignkey')
    op.drop_constraint('fk_index_jobs_current_attempt', 'index_jobs', type_='foreignkey')
    op.drop_constraint('fk_repositories_active_version', 'repositories', type_='foreignkey')
    op.drop_index('ix_references_target', table_name='references')
    op.drop_index('ix_references_source', table_name='references')
    op.drop_table('references')
    op.drop_index('ix_graph_edges_reverse', table_name='graph_edges')
    op.drop_index('ix_graph_edges_forward', table_name='graph_edges')
    op.drop_table('graph_edges')
    op.drop_index('ix_evaluation_results_run', table_name='evaluation_results')
    op.drop_table('evaluation_results')
    op.drop_index('ix_endpoints_route', table_name='endpoints')
    op.drop_table('endpoints')
    op.drop_table('citations')
    op.drop_index('ix_trace_events_order', table_name='agent_trace_events')
    op.drop_table('agent_trace_events')
    op.drop_index('ix_symbols_name', table_name='symbols')
    op.drop_table('symbols')
    op.drop_index('ix_job_attempts_stale_lease', table_name='job_attempts', postgresql_where=sa.text("state IN ('claimed', 'running')"))
    op.drop_table('job_attempts')
    op.drop_table('graph_nodes')
    op.drop_table('graph_candidates')
    op.drop_index('ix_evidence_source', table_name='evidence')
    op.drop_table('evidence')
    op.drop_table('claims')
    op.drop_index('ix_chunks_source', table_name='chunks')
    op.drop_table('chunks')
    op.drop_table('capability_readiness')
    op.drop_table('agent_traces')
    op.drop_index('ix_validation_issues_version_severity', table_name='validation_issues')
    op.drop_table('validation_issues')
    op.drop_index('ix_messages_order', table_name='messages')
    op.drop_table('messages')
    op.drop_index('uq_index_jobs_one_active', table_name='index_jobs', postgresql_where=sa.text("state IN ('queued', 'running')"))
    op.drop_index('ix_index_jobs_repository_history', table_name='index_jobs')
    op.drop_index('ix_index_jobs_recovery', table_name='index_jobs', postgresql_where=sa.text("state IN ('queued', 'running')"))
    op.drop_table('index_jobs')
    op.drop_index('ix_index_artifacts_manifest', table_name='index_artifacts')
    op.drop_table('index_artifacts')
    op.drop_index('ix_files_path', table_name='files')
    op.drop_table('files')
    op.drop_index('ix_evaluation_runs_recent', table_name='evaluation_runs')
    op.drop_table('evaluation_runs')
    op.drop_index('uq_index_versions_one_active', table_name='index_versions', postgresql_where=sa.text("lifecycle = 'active'"))
    op.drop_index('ix_index_versions_repository_history', table_name='index_versions')
    op.drop_table('index_versions')
    op.drop_index('ix_import_sessions_principal_history', table_name='import_sessions')
    op.drop_index('ix_import_sessions_expiry', table_name='import_sessions', postgresql_where=sa.text("(state NOT IN ('confirmed', 'cancelled', 'expired', 'failed'))"))
    op.drop_table('import_sessions')
    op.drop_table('source_snapshots')
    op.drop_index('uq_repository_source_locator', table_name='repository_sources', postgresql_where=sa.text('canonical_locator IS NOT NULL'))
    op.drop_table('repository_sources')
    op.drop_index('uq_deletion_one_active', table_name='repository_deletion_operations', postgresql_where=sa.text("state IN ('queued', 'running', 'partially_failed')"))
    op.drop_table('repository_deletion_operations')
    op.drop_index('ix_conversations_recent', table_name='conversations')
    op.drop_table('conversations')
    op.drop_index('ix_audit_events_resource', table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index('ix_repositories_owner_list', table_name='repositories')
    op.drop_index('ix_repositories_lifecycle', table_name='repositories')
    op.drop_table('repositories')
    op.drop_table('operator_sessions')
    op.drop_table('operator_api_tokens')
    op.drop_table('idempotency_records')
    op.drop_table('evaluation_cases')
    op.drop_table('operator_principals')
    op.drop_table('evaluation_datasets')
    # ### end Alembic commands ###
